from fastapi import WebSocket
from langchain_core.callbacks import AsyncCallbackHandler
from typing import Any, Dict, List
import asyncio


class WebSocketTokenHandler(AsyncCallbackHandler):
    """
    Async callback handler for streaming LLM tokens over WebSocket.
    Handles token streaming, cancellation, and error reporting.
    """
    def __init__(self, websocket: WebSocket):
        self.websocket = websocket
        self.final_text = ""
        self.cancelled = False
        self.token_count = 0

    async def on_chat_model_start(
        self, 
        serialized: Dict[str, Any],
        messages: List[List[Any]],
        **kwargs: Any,
    ) -> None:
        """Called when the chat model starts processing."""
        await self.websocket.send_json({
            "event": "model_start",
            "data": {
                "timestamp": asyncio.get_event_loop().time()
            }
        })
    
    async def on_llm_new_token(self, token: str, **kwargs):
        """
        Called when a new token is generated by the LLM.
        Streams the token to the WebSocket client in real-time.
        """
        if self.cancelled:
            raise Exception("Generation cancelled by user")
        
        self.final_text += token
        self.token_count += 1
        
        await self.websocket.send_json({
            "event": "token",
            "data": {
                "token": token,
                "token_count": self.token_count,
                "partial_text": self.final_text
            }
        })

    async def on_llm_end(self, response: Any, **kwargs: Any) -> None:
        """Called when the LLM finishes generating."""
        await self.websocket.send_json({
            "event": "model_end",
            "data": {
                "total_tokens": self.token_count,
                "final_text": self.final_text
            }
        })

    async def on_llm_error(self, error: Exception, **kwargs: Any) -> None:
        """Called when an error occurs during generation."""
        await self.websocket.send_json({
            "event": "error",
            "data": {
                "error": str(error),
                "token_count": self.token_count
            }
        })

    def cancel(self):
        """Cancels the generation process."""
        self.cancelled = True


