"""description

Revision ID: bb4a426f0f21
Revises: 001_add_stripe_fields
Create Date: 2025-12-31 15:16:58.173710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4a426f0f21'
down_revision: Union[str, Sequence[str], None] = '001_add_stripe_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=b'I01\n')
    op.drop_index(op.f('idx_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('idx_users_stripe_customer_id_unique'), table_name='users', postgresql_where='(stripe_customer_id IS NOT NULL)')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('idx_users_stripe_customer_id_unique'), 'users', ['stripe_customer_id'], unique=True, postgresql_where='(stripe_customer_id IS NOT NULL)')
    op.create_index(op.f('idx_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###
